version: "3.8"

services:
  local-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: spring-security-practice
    volumes:
      - ./db/mysql/data:/var/lib/mysql
    ports:
      - "3306:3306"
